baseURL = 'https://wizardly-lichterman-1650ba.netlify.app'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true